version: "3.9"
services:
  redis:
    container_name: "nexus_redis_db"
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always
  mongo:
    container_name: "nexus_mongo_db"
    image: "mongo:latest"
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: nexus
  app:
    container_name: "nexus_server"
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo
    image: "golang:latest"
    ports:
      - "8000:8000"

networks:
  default:
    name: nexus_default_network
