version: "3.9"
services:
  redis:
    container_name: "kavka_redis_db"
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
  mongo:
    container_name: "kavka_mongo_db"
    image: "mongo:latest"
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: kavka
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
  app:
    container_name: "kavka_server"
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo
    image: "golang:latest"
    ports:
      - "8000:8000"

networks:
  default:
    name: kavka_default_network
