app_name: "kavka"

http:
    host: "0.0.0.0"
    port: 3000
    cors:
        allow_origins: "*"

mongo:
    host: "127.0.0.1"
    username: "test"
    password: "test"
    port: 27017
    db_name: "kavka"

redis:
    host: "127.0.0.1"
    username: "redis"
    password:
    port: 6379
    db: 0

minio:
    endpoint: 127.0.0.1:9000
    access_key: uD3h2W3CONpYe8Tb4nbp
    secret_key: fKF98iAk1eDSpdtdJWcJHgivjpF4Su4HCdgkpYvQ

sms:

logger:
    file_name: kavka.logs
    level: debug
    targets: [console, file]
    max_size: 10
    max_backups: 1
    compress: false

nats:
    url: 127.0.0.1:4222
