app_name: "kavka"
http:
  host: "0.0.0.0"
  port: 3000
  cors:
    allow_origins: "*"
mongo:
  host: "127.0.0.1"
  username: "test"
  password: "test"
  port: 27017
  db_name: "test"
redis:
  host: "127.0.0.1"
  username: "redis"
  password:
  port: 6379
  db: 1
minio:
  endpoint: 127.0.0.1:9000
  access_key: uD3h2W3CONpYe8Tb4nbp
  secret_key: fKF98iAk1eDSpdtdJWcJHgivjpF4Su4HCdgkpYvQ

