name: Proto Buf Linter Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.4'

    - name: Install Buf Cli
    - run: go install github.com/bufbuild/buf/cmd/buf@v1.33.0

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run linter
      run: make buf_lint
