name: Go Build Source

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        go-version: '1.22.4'
    - name: Installing dependencies
      run: go mod tidy
    - name: Build source
      run: |
        if [ runner.os == "windows" ]; then
          # FIXME - Add windows builder script!
        else
          make build
        fi